/**
 * LLM API Keys Component
 *
 * WHY: Manage LLM API keys for BYOL (Bring Your Own License) providers.
 *
 * WHAT IT SHOWS:
 * - Tabs for different providers (OpenAI, Anthropic, Google)
 * - List of API keys per provider with active status
 * - Add/edit/delete key functionality
 * - Key validation feedback
 * - Masked key display with option to view full key
 */

import { useState } from 'react';
import { Key, Plus, Check, Trash2, AlertCircle, Loader2 } from 'lucide-react';
import { SettingsSection } from './settings-section';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import * as Dialog from '@radix-ui/react-dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { gql } from '@apollo/client';
import { useQuery, useMutation } from '@apollo/client/react';
import { useWorkspaceId } from '@/stores/workspaceStore';
import { useNotification } from '@/contexts/NotificationContext';
import { format } from 'date-fns';

// These will be generated by codegen after running npm run codegen
// For now, we'll use placeholder types
type LLMProvider = 'OPENAI' | 'ANTHROPIC' | 'GOOGLE';

interface LLMAPIKey {
  id: string;
  provider: LLMProvider;
  maskedKey: string;
  isActive: boolean;
  createdAt: string;
  updatedAt?: string;
  lastValidatedAt?: string;
}

// Placeholder for GraphQL documents - will be replaced with generated ones
const GET_LLM_API_KEYS = gql`
  query GetLLMAPIKeys($workspaceId: ID!) {
    workspace(id: $workspaceId) {
      id
      llmApiKeys {
        id
        provider
        maskedKey
        isActive
        createdAt
        updatedAt
        lastValidatedAt
      }
    }
  }
`;

const CREATE_LLM_API_KEY = gql`
  mutation CreateLLMAPIKey($workspaceId: ID!, $provider: LLMProvider!, $apiKey: String!) {
    createLLMAPIKey(workspaceId: $workspaceId, provider: $provider, apiKey: $apiKey) {
      id
      provider
      maskedKey
      isActive
      createdAt
      lastValidatedAt
    }
  }
`;

const UPDATE_LLM_API_KEY = gql`
  mutation UpdateLLMAPIKey($id: ID!, $apiKey: String!) {
    updateLLMAPIKey(id: $id, apiKey: $apiKey) {
      id
      provider
      maskedKey
      isActive
      updatedAt
      lastValidatedAt
    }
  }
`;

const DELETE_LLM_API_KEY = gql`
  mutation DeleteLLMAPIKey($id: ID!) {
    deleteLLMAPIKey(id: $id) {
      id
    }
  }
`;

const SET_ACTIVE_LLM_API_KEY = gql`
  mutation SetActiveLLMAPIKey($id: ID!) {
    setActiveLLMAPIKey(id: $id) {
      id
      isActive
    }
  }
`;

const PROVIDER_INFO = {
  OPENAI: {
    name: 'OpenAI',
    placeholder: 'sk-...',
    description: 'Enter your OpenAI API key (starts with sk-)',
    docsUrl: 'https://platform.openai.com/api-keys',
  },
  ANTHROPIC: {
    name: 'Anthropic',
    placeholder: 'sk-ant-...',
    description: 'Enter your Anthropic API key (starts with sk-ant-)',
    docsUrl: 'https://console.anthropic.com/settings/keys',
  },
  GOOGLE: {
    name: 'Google',
    placeholder: 'AIza...',
    description: 'Enter your Google AI API key',
    docsUrl: 'https://aistudio.google.com/apikey',
  },
} as const;

export function LLMAPIKeysSection() {
  const [selectedProvider, setSelectedProvider] = useState<LLMProvider>('OPENAI');
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [showEditDialog, setShowEditDialog] = useState(false);
  const [editingKey, setEditingKey] = useState<LLMAPIKey | null>(null);
  const [newApiKey, setNewApiKey] = useState('');
  const workspaceId = useWorkspaceId();
  const { toast } = useNotification();

  const { data, loading, refetch } = useQuery(GET_LLM_API_KEYS, {
    variables: { workspaceId: workspaceId || '' },
    skip: !workspaceId,
  });

  const [createKey, { loading: creating }] = useMutation(CREATE_LLM_API_KEY, {
    onCompleted: () => {
      toast({ description: 'API key added and validated successfully', variant: 'success' });
      setShowAddDialog(false);
      setNewApiKey('');
      refetch();
    },
    onError: (error: Error) => {
      toast({ description: error.message || 'Failed to add API key', variant: 'error' });
    },
  });

  const [updateKey, { loading: updating }] = useMutation(UPDATE_LLM_API_KEY, {
    onCompleted: () => {
      toast({ description: 'API key updated and validated successfully', variant: 'success' });
      setShowEditDialog(false);
      setEditingKey(null);
      setNewApiKey('');
      refetch();
    },
    onError: (error: Error) => {
      toast({ description: error.message || 'Failed to update API key', variant: 'error' });
    },
  });

  const [deleteKey] = useMutation(DELETE_LLM_API_KEY, {
    onCompleted: () => {
      toast({ description: 'API key deleted successfully', variant: 'success' });
      refetch();
    },
    onError: (error: Error) => {
      toast({ description: error.message || 'Failed to delete API key', variant: 'error' });
    },
  });

  const [setActiveKey] = useMutation(SET_ACTIVE_LLM_API_KEY, {
    onCompleted: () => {
      toast({ description: 'Active API key updated', variant: 'success' });
      refetch();
    },
    onError: (error: Error) => {
      toast({ description: error.message || 'Failed to set active key', variant: 'error' });
    },
  });

  const handleAddKey = async () => {
    if (!newApiKey.trim() || !workspaceId) return;

    await createKey({
      variables: {
        workspaceId,
        provider: selectedProvider,
        apiKey: newApiKey.trim(),
      },
    });
  };

  const handleUpdateKey = async () => {
    if (!newApiKey.trim() || !editingKey) return;

    await updateKey({
      variables: {
        id: editingKey.id,
        apiKey: newApiKey.trim(),
      },
    });
  };

  const handleDeleteKey = async (key: LLMAPIKey) => {
    if (!confirm(`Are you sure you want to delete this ${PROVIDER_INFO[key.provider].name} API key?`)) {
      return;
    }

    await deleteKey({ variables: { id: key.id } });
  };

  const handleSetActive = async (key: LLMAPIKey) => {
    await setActiveKey({ variables: { id: key.id } });
  };

  const handleEditKey = (key: LLMAPIKey) => {
    setEditingKey(key);
    setNewApiKey('');
    setShowEditDialog(true);
  };

  const llmApiKeys = ((data as { workspace?: { llmApiKeys?: LLMAPIKey[] } })?.workspace?.llmApiKeys || []) as LLMAPIKey[];
  const providerKeys = llmApiKeys.filter((k) => k.provider === selectedProvider);

  return (
    <SettingsSection
      title="LLM API Keys"
      description="Manage your own API keys for OpenAI, Anthropic, and Google AI providers."
      icon={Key}
    >
      <div className="space-y-6">
        {/* Provider Tabs */}
        <Tabs value={selectedProvider} onValueChange={(v) => setSelectedProvider(v as LLMProvider)}>
          <div className="flex items-center justify-between mb-4">
            <TabsList>
              <TabsTrigger value="OPENAI">OpenAI</TabsTrigger>
              <TabsTrigger value="ANTHROPIC">Anthropic</TabsTrigger>
              <TabsTrigger value="GOOGLE">Google</TabsTrigger>
            </TabsList>

            <Button size="sm" onClick={() => setShowAddDialog(true)}>
              <Plus className="h-4 w-4 mr-2" />
              Add Key
            </Button>
          </div>

          {['OPENAI', 'ANTHROPIC', 'GOOGLE'].map((provider) => (
            <TabsContent key={provider} value={provider} className="space-y-4">
              {loading ? (
                <div className="text-center py-8 text-gray-500">
                  <Loader2 className="h-6 w-6 animate-spin mx-auto mb-2" />
                  Loading keys...
                </div>
              ) : providerKeys.length > 0 ? (
                <div className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
                      <tr>
                        <th className="text-left px-4 py-3 font-medium text-gray-700 dark:text-gray-300">
                          API Key
                        </th>
                        <th className="text-left px-4 py-3 font-medium text-gray-700 dark:text-gray-300">
                          Status
                        </th>
                        <th className="text-left px-4 py-3 font-medium text-gray-700 dark:text-gray-300">
                          Last Validated
                        </th>
                        <th className="text-right px-4 py-3 font-medium text-gray-700 dark:text-gray-300">
                          Actions
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                      {providerKeys.map((key) => (
                        <tr key={key.id} className="bg-white dark:bg-gray-900">
                          <td className="px-4 py-3 font-mono text-xs text-gray-700 dark:text-gray-300">
                            {key.maskedKey}
                          </td>
                          <td className="px-4 py-3">
                            {key.isActive ? (
                              <Badge variant="success" className="gap-1">
                                <Check className="h-3 w-3" />
                                Active
                              </Badge>
                            ) : (
                              <Badge variant="secondary">Inactive</Badge>
                            )}
                          </td>
                          <td className="px-4 py-3 text-gray-600 dark:text-gray-400">
                            {key.lastValidatedAt
                              ? format(new Date(key.lastValidatedAt), 'MMM d, yyyy')
                              : 'Never'}
                          </td>
                          <td className="px-4 py-3">
                            <div className="flex justify-end gap-2">
                              {!key.isActive && (
                                <Button
                                  size="sm"
                                  variant="ghost"
                                  onClick={() => handleSetActive(key)}
                                  className="h-8 px-3 text-cyan-600 hover:text-cyan-700 hover:bg-cyan-50 dark:hover:bg-cyan-900/20"
                                >
                                  Set Active
                                </Button>
                              )}
                              <Button
                                size="sm"
                                variant="ghost"
                                onClick={() => handleEditKey(key)}
                                className="h-8 px-3"
                              >
                                Edit
                              </Button>
                              <Button
                                size="sm"
                                variant="ghost"
                                onClick={() => handleDeleteKey(key)}
                                className="h-8 px-3 text-red-600 hover:text-red-700 hover:bg-red-50 dark:hover:bg-red-900/20"
                              >
                                <Trash2 className="h-4 w-4" />
                              </Button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-12 border border-dashed border-gray-300 dark:border-gray-700 rounded-lg">
                  <div className="bg-cyan-50 dark:bg-cyan-900/20 rounded-full p-4 mb-4">
                    <AlertCircle className="h-8 w-8 text-cyan-600 dark:text-cyan-400" />
                  </div>
                  <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                    No {PROVIDER_INFO[provider as LLMProvider].name} Keys
                  </h4>
                  <p className="text-sm text-gray-600 dark:text-gray-400 text-center max-w-md mb-4">
                    Add your {PROVIDER_INFO[provider as LLMProvider].name} API key to enable AI features.
                  </p>
                  <Button size="sm" onClick={() => setShowAddDialog(true)}>
                    <Plus className="h-4 w-4 mr-2" />
                    Add {PROVIDER_INFO[provider as LLMProvider].name} Key
                  </Button>
                </div>
              )}

              {/* Provider Info */}
              <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                <div className="flex gap-3">
                  <AlertCircle className="h-5 w-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
                  <div className="text-sm">
                    <p className="font-medium text-blue-900 dark:text-blue-100 mb-1">
                      About {PROVIDER_INFO[provider as LLMProvider].name} API Keys
                    </p>
                    <p className="text-blue-700 dark:text-blue-300 mb-2">
                      {PROVIDER_INFO[provider as LLMProvider].description}
                    </p>
                    <a
                      href={PROVIDER_INFO[provider as LLMProvider].docsUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 dark:text-blue-400 hover:underline"
                    >
                      Get your API key →
                    </a>
                  </div>
                </div>
              </div>
            </TabsContent>
          ))}
        </Tabs>
      </div>

      {/* Add Key Dialog */}
      <Dialog.Root open={showAddDialog} onOpenChange={setShowAddDialog}>
        <Dialog.Portal>
          <Dialog.Overlay className="fixed inset-0 bg-black/50" />
          <Dialog.Content className="fixed left-1/2 top-1/2 max-h-[85vh] w-[90vw] max-w-[450px] -translate-x-1/2 -translate-y-1/2 rounded-lg bg-white p-6 shadow-lg">
            <Dialog.Title className="text-lg font-semibold">
              Add {PROVIDER_INFO[selectedProvider].name} API Key
            </Dialog.Title>
            <Dialog.Description className="mt-2 text-sm text-gray-600">
              {PROVIDER_INFO[selectedProvider].description}
            </Dialog.Description>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="api-key">API Key</Label>
              <Input
                id="api-key"
                type="password"
                placeholder={PROVIDER_INFO[selectedProvider].placeholder}
                value={newApiKey}
                onChange={(e) => setNewApiKey(e.target.value)}
                disabled={creating}
              />
            </div>

            <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
              <div className="flex gap-2">
                <AlertCircle className="h-4 w-4 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
                <p className="text-xs text-yellow-700 dark:text-yellow-300">
                  Your API key will be encrypted and validated before saving. It will never be displayed in full after creation.
                </p>
              </div>
            </div>
          </div>

            <div className="mt-6 flex justify-end gap-2">
              <Button variant="outline" onClick={() => setShowAddDialog(false)} disabled={creating}>
                Cancel
              </Button>
              <Button onClick={handleAddKey} disabled={creating || !newApiKey.trim()}>
                {creating ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Validating...
                  </>
                ) : (
                  'Add Key'
                )}
              </Button>
            </div>
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>

      {/* Edit Key Dialog */}
      <Dialog.Root open={showEditDialog} onOpenChange={setShowEditDialog}>
        <Dialog.Portal>
          <Dialog.Overlay className="fixed inset-0 bg-black/50" />
          <Dialog.Content className="fixed left-1/2 top-1/2 max-h-[85vh] w-[90vw] max-w-[450px] -translate-x-1/2 -translate-y-1/2 rounded-lg bg-white p-6 shadow-lg">
            <Dialog.Title className="text-lg font-semibold">
              Update {editingKey && PROVIDER_INFO[editingKey.provider].name} API Key
            </Dialog.Title>
            <Dialog.Description className="mt-2 text-sm text-gray-600">
              Enter a new API key to replace the existing one.
            </Dialog.Description>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="edit-api-key">New API Key</Label>
              <Input
                id="edit-api-key"
                type="password"
                placeholder={editingKey ? PROVIDER_INFO[editingKey.provider].placeholder : ''}
                value={newApiKey}
                onChange={(e) => setNewApiKey(e.target.value)}
                disabled={updating}
              />
            </div>

            <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
              <div className="flex gap-2">
                <AlertCircle className="h-4 w-4 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" />
                <p className="text-xs text-yellow-700 dark:text-yellow-300">
                  The new API key will be encrypted and validated before saving.
                </p>
              </div>
            </div>
          </div>

            <div className="mt-6 flex justify-end gap-2">
              <Button
                variant="outline"
                onClick={() => {
                  setShowEditDialog(false);
                  setEditingKey(null);
                  setNewApiKey('');
                }}
                disabled={updating}
              >
                Cancel
              </Button>
              <Button onClick={handleUpdateKey} disabled={updating || !newApiKey.trim()}>
                {updating ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Validating...
                  </>
                ) : (
                  'Update Key'
                )}
              </Button>
            </div>
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>
    </SettingsSection>
  );
}
