#!/bin/sh
set -e

# Configuration
KEYS_DIR=${KEYS_DIR:-/keys}

echo "🔐 2ly Runtime Entrypoint - Key Management"
echo "=========================================="
echo "Keys directory: $KEYS_DIR"
echo ""

# Priority 1: Use ENV variables if MASTER_KEY is provided
if [ -n "$MASTER_KEY" ]; then
  echo "✅ Using MASTER_KEY from environment variables"
  echo ""

# Priority 2: Load existing keys from shared directory
elif [ -f "$KEYS_DIR/.env.generated" ]; then
  echo "✅ Loading keys from $KEYS_DIR/.env.generated"
  echo ""

else
  echo "❌ ERROR: No MASTER_KEY available!"
  echo ""
  echo "Runtime requires MASTER_KEY to operate."
  echo ""
  echo "How to fix:"
  echo "  1. Local development: Run 'npm run setup-local' to generate keys"
  echo "  2. Docker: Ensure infrastructure is started with 'npm run start:dev'"
  echo "     (Backend auto-generates keys that runtime will consume)"
  echo "  3. Production: Provide MASTER_KEY via environment variable"
  echo ""
  echo "Note: Runtime consumes keys generated by backend. Ensure backend"
  echo "      starts first or keys are pre-generated."
  echo ""
  exit 1
fi

# Source generated keys from .env.generated (only if ENV vars not already set)
if [ -f "$KEYS_DIR/.env.generated" ]; then
  echo "📥 Loading environment variables from $KEYS_DIR/.env.generated"

  # Read line by line and only export if variable not already set
  while IFS='=' read -r key value || [ -n "$key" ]; do
    # Skip empty lines and comments
    case "$key" in
      ''|'#'*) continue ;;
    esac

    # Only export if not already set (ENV variables take precedence)
    if eval "[ -z \"\$$key\" ]"; then
      export "$key=$value"
    fi
  done < "$KEYS_DIR/.env.generated"

  echo "✅ Environment variables loaded"
  echo ""
fi

# Fix permissions if running as root and SERVICE_USER is set
if [ "$(id -u)" = "0" ] && [ -n "$SERVICE_USER" ]; then
  echo "🔧 Fixing ownership of $KEYS_DIR for $SERVICE_USER..."
  chown -R "$SERVICE_USER:$SERVICE_USER" "$KEYS_DIR" 2>/dev/null || true
  chown -R "$SERVICE_USER:$SERVICE_USER" /app 2>/dev/null || true

  echo "🔄 Dropping privileges to $SERVICE_USER..."
  echo ""
  echo "Starting runtime..."
  exec su-exec "$SERVICE_USER" "$@"
fi

echo "Starting runtime..."
exec "$@"
