name: Deploy to Kubernetes

on:
  # Auto-run disabled - manual trigger only
  # workflow_run:
  #   workflows: ['Build and Push Docker Images']
  #   types:
  #     - completed
  #   branches: [main, develop]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (main or develop)'
        required: true
        type: choice
        options:
          - main
          - develop
      sha:
        description: 'Commit SHA to deploy (short format, e.g., abc1234)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_INFOMANIAK }}"
          echo "${{ secrets.KUBECONFIG_INFOMANIAK }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set namespace variable
        id: set-namespace
        run: |
          if [ "${{ inputs.branch }}" = "main" ]; then
            echo "NAMESPACE=main-2ly" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
          else
            echo "NAMESPACE=dev-2ly" >> $GITHUB_ENV
            echo "BRANCH=develop" >> $GITHUB_ENV
          fi

      - name: Set short SHA
        run: echo "SHORT_SHA=${{ inputs.sha }}" >> $GITHUB_ENV

      - name: Update image in Kubernetes
        run: |
          echo "NAMESPACE: $NAMESPACE"
          echo "BRANCH: $BRANCH"
          echo "SHORT_SHA: $SHORT_SHA"
          kubectl set image deployment/backend-deployment backend=ghcr.io/${{ github.repository }}/backend:$BRANCH-$SHORT_SHA -n $NAMESPACE
          kubectl set image deployment/frontend-deployment frontend=ghcr.io/${{ github.repository }}/frontend:$BRANCH-$SHORT_SHA -n $NAMESPACE
          # kubectl set image deployment/runtime-deployment runtime=ghcr.io/${{ github.repository }}/runtime:$BRANCH-$SHORT_SHA -n $NAMESPACE

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/backend-deployment -n $NAMESPACE
          kubectl rollout status deployment/frontend-deployment -n $NAMESPACE
